// Generate a thematic catalogue guide via Claude (Anthropic API)
import { corsHeaders } from 'npm:@supabase/supabase-js@2/cors';

const BASE_SYSTEM_PROMPT = `You are the AI assistant inside Fjord & Waves Travel Itinerary Engine. You work as a premium boutique travel designer and editorial travel writer.

You are writing a CATALOGUE GUIDE — a thematic, editorial travel guide for a destination. This is NOT a day-by-day itinerary. There are NO "Day 1", "Day 2", "Morning", "Afternoon", or "Evening" headers anywhere in the output. Never use day numbering or time-of-day sub-sections.

Instead, organise the entire guide into thematic sections that help a traveller understand and explore the destination. Choose section titles that genuinely fit the destination and experience type — not every section applies to every place. Use only the sections that make sense; rename them naturally when appropriate.

Typical sections to choose from (pick 4–7 of these, adapt freely):

- Where to Stay — neighbourhoods or areas worth basing yourself in, and the general style of accommodation that suits the destination. This is a high-level overview of areas only; do NOT recommend specific hotels here (specific hotels are handled in a separate Hotel Recommendations section).
- Getting Around — transport, logistics, how locals actually move, what to book in advance, what to avoid.
- Must-See Highlights — the iconic places and experiences, with short, specific context on each (why it matters, when to go, how to experience it well).
- Hidden Gems & Local Favourites — less obvious spots and local tips most visitors miss.
- Food & Drink — where to eat, what to try, local specialties, named dishes and addresses.
- Experiences & Activities — things to do that fit the destination (hikes, tours, classes, nightlife, cultural moments, etc.).
- Practical Tips — best time to visit, what to pack, booking advice, things to watch out for.

For a city break, lean into neighbourhoods, food and culture. For a nature trip, lean into routes, seasons, hikes and weather. Adapt section titles and order to the destination — never copy this list mechanically.

CONTENT RULES:

Each section must contain 2–4 short paragraphs.

Each paragraph is 2–4 sentences and covers ONE specific place, activity, dish or topic. Use bold inline labels at the start of paragraphs when it helps the reader scan (e.g. **Grünerløkka** — short, specific paragraph...).

Be concrete and specific: name exact streets, neighbourhoods, dishes, viewpoints, trails, restaurants, shops, time-of-year windows. Specificity is what makes a guide feel human.

Do NOT use any day numbering, day headers, or Morning / Afternoon / Evening structure.

Do NOT include closing remarks like "this guide will leave you with memories to cherish".

Begin with a short editorial introduction (maximum 2 short paragraphs) that captures the soul of the destination, then go straight into the first thematic section.

Format the output using clean markdown:
- Use \`##\` for each thematic section title.
- Use short paragraphs separated by blank lines.
- Use bold for inline place names where useful.
- Do NOT use \`#\` (the title is rendered separately).
- Do NOT wrap output in code fences.

WRITING STYLE — HUMAN AND NATURAL:

Write the way an experienced, well-travelled human advisor would speak to a trusted client over a coffee. The writing must feel personal, grounded and real — never like it was generated by an AI.

STRICTLY AVOID:

Words like: tapestry, nestled, vibrant, bustling, charming, seamlessly, delve, curated, elevate, timeless, unparalleled, testament, journey of discovery, treasure trove, gem, haven, boasts, offers a unique blend

Opening sentences that start with "Imagine..." or "Welcome to..."

Overly poetic or flowery descriptions that feel exaggerated

Long complex sentences packed with multiple clauses

Repetitive sentence structures throughout the document

Adjective overload — never use more than one adjective per noun

Summarising conclusions like "This will leave you with memories to cherish"

INSTEAD:

Use short, confident, specific sentences

Name exact places, streets, dishes, and experiences — specificity makes writing feel human

Alternate between short and medium length sentences naturally

Let facts and details do the emotional work — avoid telling the reader how to feel

Write as if you have personally been there and are sharing what you genuinely loved

Use occasional dry wit or warmth where it fits naturally

Trust the reader — do not over-explain or over-sell

Write in the following language: {language}

Now create the premium editorial thematic catalogue guide for:

Destination: {destination}

Experience type: {experience_type}

Trip length context (for pacing only, never as headers): {duration}

Additional notes from editor: {notes}`;

const LANG_NAMES: Record<string, string> = {
  en: 'English',
  pt: 'Brazilian Portuguese (pt-BR)',
  no: 'Norwegian (Bokmål)',
};

function buildSystemPrompt(values: {
  language: string;
  destination: string;
  experience_type: string;
  duration: string;
  notes: string;
}): string {
  return BASE_SYSTEM_PROMPT
    .replace(/{language}/g, values.language)
    .replace(/{destination}/g, values.destination || 'Not specified')
    .replace(/{experience_type}/g, values.experience_type || 'Not specified')
    .replace(/{duration}/g, values.duration || 'Not specified')
    .replace(/{notes}/g, values.notes || 'None');
}

Deno.serve(async (req) => {
  if (req.method === 'OPTIONS') return new Response('ok', { headers: corsHeaders });

  try {
    const apiKey = Deno.env.get('ANTHROPIC_API_KEY');
    if (!apiKey) {
      return new Response(JSON.stringify({ error: 'ANTHROPIC_API_KEY not configured' }), {
        status: 500,
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      });
    }

    const body = await req.json().catch(() => ({}));
    const {
      title = '',
      destination = '',
      experience_type = '',
      duration = '',
      language = 'en',
      brief = '',
      mode = 'full', // 'full' | 'section'
      section_instruction = '',
      existing_content = '',
    } = body || {};

    if (mode === 'full' && !destination && !title) {
      return new Response(JSON.stringify({ error: 'destination or title is required' }), {
        status: 400,
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      });
    }

    const langName = LANG_NAMES[language] || 'English';

    const systemPrompt = buildSystemPrompt({
      language: langName,
      destination,
      experience_type,
      duration,
      notes: brief,
    });

    // Build the sequence of user prompts (one per Anthropic call).
    const userPrompts: string[] = [];

    if (mode === 'section') {
      userPrompts.push(
        `Write the response entirely in ${langName}.\n\n` +
          `Here is an existing catalogue guide draft (markdown):\n\n` +
          `"""\n${existing_content}\n"""\n\n` +
          `Please regenerate ONLY the section described below, keeping the same overall thematic style and tone. ` +
          `Do not introduce any day-by-day or Morning/Afternoon/Evening structure. ` +
          `Return JUST the rewritten section as markdown — no preamble, no explanation.\n\n` +
          `Section instruction: ${section_instruction}`,
      );
    } else {
      // Two-pass thematic generation to keep streams flowing and avoid truncation.
      userPrompts.push(
        `Produce the premium editorial thematic catalogue guide now in markdown. ` +
          `Write the short introduction (max 2 short paragraphs), then write the FIRST HALF of the thematic sections in full ` +
          `(use \`##\` headers, no day numbering, no Morning/Afternoon/Evening). ` +
          `Stop cleanly at the end of a section — do not write a closing remark; the guide will be continued in a follow-up call.`,
      );
      userPrompts.push(
        `Continue the catalogue guide with the remaining thematic sections. ` +
          `Do not repeat the introduction or any sections already written. ` +
          `Start directly with the next \`##\` section header. ` +
          `Complete the remaining sections in full and end the document naturally — no day numbering, no Morning/Afternoon/Evening, no summarising closing remarks.`,
      );
    }

    return streamSequentialCalls({ apiKey, systemPrompt, userPrompts });
  } catch (err: any) {
    console.error('generate-catalog-itinerary error', err);
    return new Response(JSON.stringify({ error: err?.message || 'Unknown error' }), {
      status: 500,
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    });
  }
});

// Run multiple Anthropic streaming calls sequentially, forwarding text deltas
// from each as plain-text chunks to the client. Keeps the edge-function idle
// timer alive because bytes flow continuously.
function streamSequentialCalls(opts: {
  apiKey: string;
  systemPrompt: string;
  userPrompts: string[];
}): Response {
  const { apiKey, systemPrompt, userPrompts } = opts;
  const encoder = new TextEncoder();
  const decoder = new TextDecoder();

  const stream = new ReadableStream({
    async start(controller) {
      try {
        for (let i = 0; i < userPrompts.length; i++) {
          const res = await fetch('https://api.anthropic.com/v1/messages', {
            method: 'POST',
            headers: {
              'Content-Type': 'application/json',
              'x-api-key': apiKey,
              'anthropic-version': '2023-06-01',
            },
            body: JSON.stringify({
              model: 'claude-sonnet-4-5',
              max_tokens: 8192,
              stream: true,
              system: systemPrompt,
              messages: [{ role: 'user', content: userPrompts[i] }],
            }),
          });

          if (!res.ok || !res.body) {
            const errText = await res.text().catch(() => '');
            console.error('Anthropic API error', res.status, errText);
            controller.enqueue(
              encoder.encode(`\n\n[Error from upstream model (${res.status}): ${errText}]\n`),
            );
            break;
          }

          // Separate chunks with a blank line so the second call doesn't glue
          // onto the last line of the first call.
          if (i > 0) controller.enqueue(encoder.encode('\n\n'));

          const reader = res.body.getReader();
          let buffer = '';
          while (true) {
            const { value, done } = await reader.read();
            if (done) break;
            buffer += decoder.decode(value, { stream: true });
            const lines = buffer.split('\n');
            buffer = lines.pop() ?? '';
            for (const line of lines) {
              const trimmed = line.trim();
              if (!trimmed.startsWith('data:')) continue;
              const payload = trimmed.slice(5).trim();
              if (!payload || payload === '[DONE]') continue;
              try {
                const evt = JSON.parse(payload);
                if (evt.type === 'content_block_delta' && evt.delta?.type === 'text_delta') {
                  controller.enqueue(encoder.encode(evt.delta.text));
                }
              } catch { /* ignore parse errors */ }
            }
          }
        }
      } catch (e) {
        console.error('stream error', e);
      } finally {
        controller.close();
      }
    },
  });

  return new Response(stream, {
    headers: {
      ...corsHeaders,
      'Content-Type': 'text/plain; charset=utf-8',
      'X-Content-Type-Options': 'nosniff',
      'Cache-Control': 'no-cache, no-transform',
    },
  });
}
