// Generate a thematic catalogue guide via Claude (Anthropic API)
import { corsHeaders } from 'npm:@supabase/supabase-js@2/cors';

const BASE_SYSTEM_PROMPT = `You are the AI assistant inside Fjord & Waves Travel Itinerary Engine. You work as a premium boutique travel designer and editorial travel writer.

You are writing a CATALOGUE GUIDE in a DAY-BY-DAY JOURNEY format. Even though the customer's exact travel dates are not known, you must design a realistic, geographically logical sequence of days through the destination — choosing specific towns, viewpoints, restaurants, hikes and experiences in an order that genuinely makes sense as a single connected trip. Pace it like a route a knowledgeable local would draw on a map: never two long drives back-to-back, never doubling back, and with rest built in where the destination needs it.

OUTPUT STRUCTURE (in this exact order):

1. EDITORIAL INTRODUCTION
A short editorial introduction — maximum 2 short paragraphs — that captures the soul of the destination and hints at the shape of the journey. Do NOT use a heading for this; it sits at the very top.

2. TRIP OVERVIEW
A \`## Trip Overview\` section that lists the whole route at a glance, one bullet per day in the format:
- **Day 1 — Place / Area:** how you get there (e.g. arrival flight, drive, ferry, train) — one short clause.
- **Day 2 — Place / Area:** transition or stay (e.g. "stay put", "drive 2h north", "ferry to the islands").
Keep each bullet to ONE line. This is a quick visual scan of the whole trip.

3. DAY-BY-DAY BREAKDOWN
One \`## Day N — Short Theme\` heading per day (e.g. \`## Day 1 — Arrival and the Road to the Fjords\`). The day number must match the trip length implied by the duration input.

Immediately under each day heading, write ONE short italic line giving base location and, if traveling, the route, e.g.:
*Base: Bergen. From Oslo to Bergen by morning train (~7h).*

Then write 2–4 short paragraphs (2–4 sentences each) that flow as a single narrative for that day: what happens first, how the day connects to the next stop, what to do and see along the way, where to eat, and ONE insider tip woven into the prose. Logistics — drive times, ferry crossings, walking distances, booking notes — must be woven into the narrative, NOT listed in a separate logistics block. Use bold inline place names where it helps the reader scan (e.g. **Fløyen** — short phrase…).

Do NOT use Morning / Afternoon / Evening sub-headings. Do NOT use bullet lists inside day sections (the trip overview is the only bulleted block). Do NOT add a separate "Where to stay" / "Getting around" / "Highlights" / "Hidden gems" / "Food & drink" / "Experiences" section — fold all of that content into the day narrative where it belongs.

4. PRACTICAL TIPS
End with a single \`## Practical Tips\` section: 2–4 short paragraphs covering best time to visit, what to pack, booking advice, money/language basics, and any region-specific things to watch out for. No closing remarks afterwards.

FORMATTING:
- Use \`##\` only for "Trip Overview", "Day N — …" and "Practical Tips" headings.
- No \`#\` (the title is rendered separately).
- No code fences.
- Short paragraphs separated by blank lines.

WRITING STYLE — HUMAN AND NATURAL:

Write the way an experienced, well-travelled human advisor would speak to a trusted client over a coffee. The writing must feel personal, grounded and real — never like it was generated by an AI.

STRICTLY AVOID:
Words like: tapestry, nestled, vibrant, bustling, charming, seamlessly, delve, curated, elevate, timeless, unparalleled, testament, journey of discovery, treasure trove, gem, haven, boasts, offers a unique blend.
Opening sentences that start with "Imagine..." or "Welcome to...".
Overly poetic or flowery descriptions, long complex sentences, repetitive sentence structures, adjective overload (never more than one adjective per noun), and summarising conclusions like "this will leave you with memories to cherish".

INSTEAD:
Use short, confident, specific sentences. Name exact places, streets, dishes, viewpoints, trails, restaurants, time windows. Alternate short and medium sentences naturally. Let facts and details do the emotional work — avoid telling the reader how to feel. Write as if you have personally been there.

Write the entire response in: {language}

Now create the day-by-day catalogue journey for:

Destination: {destination}
Experience type: {experience_type}
Trip length: {duration}
Additional notes from editor: {notes}`;

const LANG_NAMES: Record<string, string> = {
  en: 'English',
  pt: 'Brazilian Portuguese (pt-BR)',
  no: 'Norwegian (Bokmål)',
};

function buildSystemPrompt(values: {
  language: string;
  destination: string;
  experience_type: string;
  duration: string;
  notes: string;
}): string {
  return BASE_SYSTEM_PROMPT
    .replace(/{language}/g, values.language)
    .replace(/{destination}/g, values.destination || 'Not specified')
    .replace(/{experience_type}/g, values.experience_type || 'Not specified')
    .replace(/{duration}/g, values.duration || 'Not specified')
    .replace(/{notes}/g, values.notes || 'None');
}

Deno.serve(async (req) => {
  if (req.method === 'OPTIONS') return new Response('ok', { headers: corsHeaders });

  try {
    const apiKey = Deno.env.get('ANTHROPIC_API_KEY');
    if (!apiKey) {
      return new Response(JSON.stringify({ error: 'ANTHROPIC_API_KEY not configured' }), {
        status: 500,
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      });
    }

    const body = await req.json().catch(() => ({}));
    const {
      title = '',
      destination = '',
      experience_type = '',
      duration = '',
      language = 'en',
      brief = '',
      mode = 'full', // 'full' | 'section'
      section_instruction = '',
      existing_content = '',
    } = body || {};

    if (mode === 'full' && !destination && !title) {
      return new Response(JSON.stringify({ error: 'destination or title is required' }), {
        status: 400,
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      });
    }

    const langName = LANG_NAMES[language] || 'English';

    const systemPrompt = buildSystemPrompt({
      language: langName,
      destination,
      experience_type,
      duration,
      notes: brief,
    });

    // Build the sequence of user prompts (one per Anthropic call).
    const userPrompts: string[] = [];

    if (mode === 'section') {
      userPrompts.push(
        `Write the response entirely in ${langName}.\n\n` +
          `Here is an existing catalogue guide draft (markdown), already in day-by-day format:\n\n` +
          `"""\n${existing_content}\n"""\n\n` +
          `Please regenerate ONLY the section described below, keeping the same day-by-day journey style, tone and conventions ` +
          `(no Morning/Afternoon/Evening sub-headings, logistics woven into narrative, 2–4 short paragraphs per day). ` +
          `Return JUST the rewritten section as markdown — no preamble, no explanation.\n\n` +
          `Section instruction: ${section_instruction}`,
      );
    } else {
      // Two-pass day-by-day generation to keep streams flowing and avoid truncation.
      userPrompts.push(
        `Produce the day-by-day catalogue journey now in markdown. ` +
          `Write the short editorial introduction (max 2 short paragraphs), then the \`## Trip Overview\` bullet list covering EVERY day of the trip, ` +
          `then the FIRST HALF of the day-by-day sections in full (\`## Day N — Theme\` headings, italic base/route line, then 2–4 short narrative paragraphs each). ` +
          `Stop cleanly at the end of a day — do not write Practical Tips yet; the guide will be continued in a follow-up call.`,
      );
      userPrompts.push(
        `Continue the day-by-day catalogue journey. ` +
          `Do not repeat the introduction, the trip overview, or any days already written. ` +
          `Start directly with the next \`## Day N — Theme\` heading and complete all remaining days, then write the final \`## Practical Tips\` section. ` +
          `End naturally — no closing remarks.`,
      );
    }

    return streamSequentialCalls({ apiKey, systemPrompt, userPrompts });
  } catch (err: any) {
    console.error('generate-catalog-itinerary error', err);
    return new Response(JSON.stringify({ error: err?.message || 'Unknown error' }), {
      status: 500,
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    });
  }
});

// Run multiple Anthropic streaming calls sequentially, forwarding text deltas
// from each as plain-text chunks to the client. Keeps the edge-function idle
// timer alive because bytes flow continuously.
function streamSequentialCalls(opts: {
  apiKey: string;
  systemPrompt: string;
  userPrompts: string[];
}): Response {
  const { apiKey, systemPrompt, userPrompts } = opts;
  const encoder = new TextEncoder();
  const decoder = new TextDecoder();

  const stream = new ReadableStream({
    async start(controller) {
      try {
        for (let i = 0; i < userPrompts.length; i++) {
          const res = await fetch('https://api.anthropic.com/v1/messages', {
            method: 'POST',
            headers: {
              'Content-Type': 'application/json',
              'x-api-key': apiKey,
              'anthropic-version': '2023-06-01',
            },
            body: JSON.stringify({
              model: 'claude-sonnet-4-5',
              max_tokens: 8192,
              stream: true,
              system: systemPrompt,
              messages: [{ role: 'user', content: userPrompts[i] }],
            }),
          });

          if (!res.ok || !res.body) {
            const errText = await res.text().catch(() => '');
            console.error('Anthropic API error', res.status, errText);
            controller.enqueue(
              encoder.encode(`\n\n[Error from upstream model (${res.status}): ${errText}]\n`),
            );
            break;
          }

          // Separate chunks with a blank line so the second call doesn't glue
          // onto the last line of the first call.
          if (i > 0) controller.enqueue(encoder.encode('\n\n'));

          const reader = res.body.getReader();
          let buffer = '';
          while (true) {
            const { value, done } = await reader.read();
            if (done) break;
            buffer += decoder.decode(value, { stream: true });
            const lines = buffer.split('\n');
            buffer = lines.pop() ?? '';
            for (const line of lines) {
              const trimmed = line.trim();
              if (!trimmed.startsWith('data:')) continue;
              const payload = trimmed.slice(5).trim();
              if (!payload || payload === '[DONE]') continue;
              try {
                const evt = JSON.parse(payload);
                if (evt.type === 'content_block_delta' && evt.delta?.type === 'text_delta') {
                  controller.enqueue(encoder.encode(evt.delta.text));
                }
              } catch { /* ignore parse errors */ }
            }
          }
        }
      } catch (e) {
        console.error('stream error', e);
      } finally {
        controller.close();
      }
    },
  });

  return new Response(stream, {
    headers: {
      ...corsHeaders,
      'Content-Type': 'text/plain; charset=utf-8',
      'X-Content-Type-Options': 'nosniff',
      'Cache-Control': 'no-cache, no-transform',
    },
  });
}
