/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Char123LocaleChar125RouteImport } from './routes/{-$locale}'
import { Route as Char123LocaleChar125IndexRouteImport } from './routes/{-$locale}/index'
import { Route as Char123LocaleChar125AboutRouteImport } from './routes/{-$locale}/about'
import { Route as Char123LocaleChar125AdminRouteImport } from './routes/{-$locale}/admin'
import { Route as Char123LocaleChar125LegalRouteImport } from './routes/{-$locale}/legal'
import { Route as Char123LocaleChar125LoginRouteImport } from './routes/{-$locale}/login'
import { Route as Char123LocaleChar125PlanMyTripRouteImport } from './routes/{-$locale}/plan-my-trip'
import { Route as Char123LocaleChar125PrivacyRouteImport } from './routes/{-$locale}/privacy'
import { Route as Char123LocaleChar125ResetPasswordRouteImport } from './routes/{-$locale}/reset-password'
import { Route as Char123LocaleChar125StartYourJourneyRouteImport } from './routes/{-$locale}/start-your-journey'
import { Route as Char123LocaleChar125TermsRouteImport } from './routes/{-$locale}/terms'
import { Route as Char123LocaleChar125ThankYouRouteImport } from './routes/{-$locale}/thank-you'
import { Route as Char123LocaleChar125UnsubscribeRouteImport } from './routes/{-$locale}/unsubscribe'
import { Route as Char123LocaleChar125CatalogueIndexRouteImport } from './routes/{-$locale}/catalogue/index'
import { Route as Char123LocaleChar125CatalogueSlugRouteImport } from './routes/{-$locale}/catalogue/$slug'
import { Route as Char123LocaleChar125CatalogueSuccessRouteImport } from './routes/{-$locale}/catalogue/success'
import { Route as Char123LocaleChar125DestinationsNorwayRouteImport } from './routes/{-$locale}/destinations/norway'
import { Route as Char123LocaleChar125ItinerariesShopIndexRouteImport } from './routes/{-$locale}/itineraries-shop/index'
import { Route as Char123LocaleChar125ItinerariesShopSlugRouteImport } from './routes/{-$locale}/itineraries-shop/$slug'
import { Route as Char123LocaleChar125ItinerariesShopSuccessRouteImport } from './routes/{-$locale}/itineraries-shop/success'
import { Route as Char123LocaleChar125RoutesIndexRouteImport } from './routes/{-$locale}/routes/index'
import { Route as Char123LocaleChar125RoutesSlugRouteImport } from './routes/{-$locale}/routes/$slug'
import { Route as Char123LocaleChar125TripTokenRouteImport } from './routes/{-$locale}/trip.$token'

const Char123LocaleChar125Route = Char123LocaleChar125RouteImport.update({
  id: '/{-$locale}',
  path: '/{-$locale}',
  getParentRoute: () => rootRouteImport,
} as any)
const Char123LocaleChar125IndexRoute =
  Char123LocaleChar125IndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => Char123LocaleChar125Route,
  } as any)
const Char123LocaleChar125AboutRoute =
  Char123LocaleChar125AboutRouteImport.update({
    id: '/about',
    path: '/about',
    getParentRoute: () => Char123LocaleChar125Route,
  } as any)
const Char123LocaleChar125AdminRoute =
  Char123LocaleChar125AdminRouteImport.update({
    id: '/admin',
    path: '/admin',
    getParentRoute: () => Char123LocaleChar125Route,
  } as any)
const Char123LocaleChar125LegalRoute =
  Char123LocaleChar125LegalRouteImport.update({
    id: '/legal',
    path: '/legal',
    getParentRoute: () => Char123LocaleChar125Route,
  } as any)
const Char123LocaleChar125LoginRoute =
  Char123LocaleChar125LoginRouteImport.update({
    id: '/login',
    path: '/login',
    getParentRoute: () => Char123LocaleChar125Route,
  } as any)
const Char123LocaleChar125PlanMyTripRoute =
  Char123LocaleChar125PlanMyTripRouteImport.update({
    id: '/plan-my-trip',
    path: '/plan-my-trip',
    getParentRoute: () => Char123LocaleChar125Route,
  } as any)
const Char123LocaleChar125PrivacyRoute =
  Char123LocaleChar125PrivacyRouteImport.update({
    id: '/privacy',
    path: '/privacy',
    getParentRoute: () => Char123LocaleChar125Route,
  } as any)
const Char123LocaleChar125ResetPasswordRoute =
  Char123LocaleChar125ResetPasswordRouteImport.update({
    id: '/reset-password',
    path: '/reset-password',
    getParentRoute: () => Char123LocaleChar125Route,
  } as any)
const Char123LocaleChar125StartYourJourneyRoute =
  Char123LocaleChar125StartYourJourneyRouteImport.update({
    id: '/start-your-journey',
    path: '/start-your-journey',
    getParentRoute: () => Char123LocaleChar125Route,
  } as any)
const Char123LocaleChar125TermsRoute =
  Char123LocaleChar125TermsRouteImport.update({
    id: '/terms',
    path: '/terms',
    getParentRoute: () => Char123LocaleChar125Route,
  } as any)
const Char123LocaleChar125ThankYouRoute =
  Char123LocaleChar125ThankYouRouteImport.update({
    id: '/thank-you',
    path: '/thank-you',
    getParentRoute: () => Char123LocaleChar125Route,
  } as any)
const Char123LocaleChar125UnsubscribeRoute =
  Char123LocaleChar125UnsubscribeRouteImport.update({
    id: '/unsubscribe',
    path: '/unsubscribe',
    getParentRoute: () => Char123LocaleChar125Route,
  } as any)
const Char123LocaleChar125CatalogueIndexRoute =
  Char123LocaleChar125CatalogueIndexRouteImport.update({
    id: '/catalogue/',
    path: '/catalogue/',
    getParentRoute: () => Char123LocaleChar125Route,
  } as any)
const Char123LocaleChar125CatalogueSlugRoute =
  Char123LocaleChar125CatalogueSlugRouteImport.update({
    id: '/catalogue/$slug',
    path: '/catalogue/$slug',
    getParentRoute: () => Char123LocaleChar125Route,
  } as any)
const Char123LocaleChar125CatalogueSuccessRoute =
  Char123LocaleChar125CatalogueSuccessRouteImport.update({
    id: '/catalogue/success',
    path: '/catalogue/success',
    getParentRoute: () => Char123LocaleChar125Route,
  } as any)
const Char123LocaleChar125DestinationsNorwayRoute =
  Char123LocaleChar125DestinationsNorwayRouteImport.update({
    id: '/destinations/norway',
    path: '/destinations/norway',
    getParentRoute: () => Char123LocaleChar125Route,
  } as any)
const Char123LocaleChar125ItinerariesShopIndexRoute =
  Char123LocaleChar125ItinerariesShopIndexRouteImport.update({
    id: '/itineraries-shop/',
    path: '/itineraries-shop/',
    getParentRoute: () => Char123LocaleChar125Route,
  } as any)
const Char123LocaleChar125ItinerariesShopSlugRoute =
  Char123LocaleChar125ItinerariesShopSlugRouteImport.update({
    id: '/itineraries-shop/$slug',
    path: '/itineraries-shop/$slug',
    getParentRoute: () => Char123LocaleChar125Route,
  } as any)
const Char123LocaleChar125ItinerariesShopSuccessRoute =
  Char123LocaleChar125ItinerariesShopSuccessRouteImport.update({
    id: '/itineraries-shop/success',
    path: '/itineraries-shop/success',
    getParentRoute: () => Char123LocaleChar125Route,
  } as any)
const Char123LocaleChar125RoutesIndexRoute =
  Char123LocaleChar125RoutesIndexRouteImport.update({
    id: '/routes/',
    path: '/routes/',
    getParentRoute: () => Char123LocaleChar125Route,
  } as any)
const Char123LocaleChar125RoutesSlugRoute =
  Char123LocaleChar125RoutesSlugRouteImport.update({
    id: '/routes/$slug',
    path: '/routes/$slug',
    getParentRoute: () => Char123LocaleChar125Route,
  } as any)
const Char123LocaleChar125TripTokenRoute =
  Char123LocaleChar125TripTokenRouteImport.update({
    id: '/trip/$token',
    path: '/trip/$token',
    getParentRoute: () => Char123LocaleChar125Route,
  } as any)

export interface FileRoutesByFullPath {
  '/{-$locale}': typeof Char123LocaleChar125RouteWithChildren
  '/{-$locale}/about': typeof Char123LocaleChar125AboutRoute
  '/{-$locale}/admin': typeof Char123LocaleChar125AdminRoute
  '/{-$locale}/legal': typeof Char123LocaleChar125LegalRoute
  '/{-$locale}/login': typeof Char123LocaleChar125LoginRoute
  '/{-$locale}/plan-my-trip': typeof Char123LocaleChar125PlanMyTripRoute
  '/{-$locale}/privacy': typeof Char123LocaleChar125PrivacyRoute
  '/{-$locale}/reset-password': typeof Char123LocaleChar125ResetPasswordRoute
  '/{-$locale}/start-your-journey': typeof Char123LocaleChar125StartYourJourneyRoute
  '/{-$locale}/terms': typeof Char123LocaleChar125TermsRoute
  '/{-$locale}/thank-you': typeof Char123LocaleChar125ThankYouRoute
  '/{-$locale}/unsubscribe': typeof Char123LocaleChar125UnsubscribeRoute
  '/{-$locale}/': typeof Char123LocaleChar125IndexRoute
  '/{-$locale}/catalogue/$slug': typeof Char123LocaleChar125CatalogueSlugRoute
  '/{-$locale}/catalogue/success': typeof Char123LocaleChar125CatalogueSuccessRoute
  '/{-$locale}/destinations/norway': typeof Char123LocaleChar125DestinationsNorwayRoute
  '/{-$locale}/itineraries-shop/$slug': typeof Char123LocaleChar125ItinerariesShopSlugRoute
  '/{-$locale}/itineraries-shop/success': typeof Char123LocaleChar125ItinerariesShopSuccessRoute
  '/{-$locale}/routes/$slug': typeof Char123LocaleChar125RoutesSlugRoute
  '/{-$locale}/trip/$token': typeof Char123LocaleChar125TripTokenRoute
  '/{-$locale}/catalogue/': typeof Char123LocaleChar125CatalogueIndexRoute
  '/{-$locale}/itineraries-shop/': typeof Char123LocaleChar125ItinerariesShopIndexRoute
  '/{-$locale}/routes/': typeof Char123LocaleChar125RoutesIndexRoute
}
export interface FileRoutesByTo {
  '/{-$locale}/about': typeof Char123LocaleChar125AboutRoute
  '/{-$locale}/admin': typeof Char123LocaleChar125AdminRoute
  '/{-$locale}/legal': typeof Char123LocaleChar125LegalRoute
  '/{-$locale}/login': typeof Char123LocaleChar125LoginRoute
  '/{-$locale}/plan-my-trip': typeof Char123LocaleChar125PlanMyTripRoute
  '/{-$locale}/privacy': typeof Char123LocaleChar125PrivacyRoute
  '/{-$locale}/reset-password': typeof Char123LocaleChar125ResetPasswordRoute
  '/{-$locale}/start-your-journey': typeof Char123LocaleChar125StartYourJourneyRoute
  '/{-$locale}/terms': typeof Char123LocaleChar125TermsRoute
  '/{-$locale}/thank-you': typeof Char123LocaleChar125ThankYouRoute
  '/{-$locale}/unsubscribe': typeof Char123LocaleChar125UnsubscribeRoute
  '/{-$locale}': typeof Char123LocaleChar125IndexRoute
  '/{-$locale}/catalogue/$slug': typeof Char123LocaleChar125CatalogueSlugRoute
  '/{-$locale}/catalogue/success': typeof Char123LocaleChar125CatalogueSuccessRoute
  '/{-$locale}/destinations/norway': typeof Char123LocaleChar125DestinationsNorwayRoute
  '/{-$locale}/itineraries-shop/$slug': typeof Char123LocaleChar125ItinerariesShopSlugRoute
  '/{-$locale}/itineraries-shop/success': typeof Char123LocaleChar125ItinerariesShopSuccessRoute
  '/{-$locale}/routes/$slug': typeof Char123LocaleChar125RoutesSlugRoute
  '/{-$locale}/trip/$token': typeof Char123LocaleChar125TripTokenRoute
  '/{-$locale}/catalogue': typeof Char123LocaleChar125CatalogueIndexRoute
  '/{-$locale}/itineraries-shop': typeof Char123LocaleChar125ItinerariesShopIndexRoute
  '/{-$locale}/routes': typeof Char123LocaleChar125RoutesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/{-$locale}': typeof Char123LocaleChar125RouteWithChildren
  '/{-$locale}/about': typeof Char123LocaleChar125AboutRoute
  '/{-$locale}/admin': typeof Char123LocaleChar125AdminRoute
  '/{-$locale}/legal': typeof Char123LocaleChar125LegalRoute
  '/{-$locale}/login': typeof Char123LocaleChar125LoginRoute
  '/{-$locale}/plan-my-trip': typeof Char123LocaleChar125PlanMyTripRoute
  '/{-$locale}/privacy': typeof Char123LocaleChar125PrivacyRoute
  '/{-$locale}/reset-password': typeof Char123LocaleChar125ResetPasswordRoute
  '/{-$locale}/start-your-journey': typeof Char123LocaleChar125StartYourJourneyRoute
  '/{-$locale}/terms': typeof Char123LocaleChar125TermsRoute
  '/{-$locale}/thank-you': typeof Char123LocaleChar125ThankYouRoute
  '/{-$locale}/unsubscribe': typeof Char123LocaleChar125UnsubscribeRoute
  '/{-$locale}/': typeof Char123LocaleChar125IndexRoute
  '/{-$locale}/catalogue/$slug': typeof Char123LocaleChar125CatalogueSlugRoute
  '/{-$locale}/catalogue/success': typeof Char123LocaleChar125CatalogueSuccessRoute
  '/{-$locale}/destinations/norway': typeof Char123LocaleChar125DestinationsNorwayRoute
  '/{-$locale}/itineraries-shop/$slug': typeof Char123LocaleChar125ItinerariesShopSlugRoute
  '/{-$locale}/itineraries-shop/success': typeof Char123LocaleChar125ItinerariesShopSuccessRoute
  '/{-$locale}/routes/$slug': typeof Char123LocaleChar125RoutesSlugRoute
  '/{-$locale}/trip/$token': typeof Char123LocaleChar125TripTokenRoute
  '/{-$locale}/catalogue/': typeof Char123LocaleChar125CatalogueIndexRoute
  '/{-$locale}/itineraries-shop/': typeof Char123LocaleChar125ItinerariesShopIndexRoute
  '/{-$locale}/routes/': typeof Char123LocaleChar125RoutesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/{-$locale}'
    | '/{-$locale}/about'
    | '/{-$locale}/admin'
    | '/{-$locale}/legal'
    | '/{-$locale}/login'
    | '/{-$locale}/plan-my-trip'
    | '/{-$locale}/privacy'
    | '/{-$locale}/reset-password'
    | '/{-$locale}/start-your-journey'
    | '/{-$locale}/terms'
    | '/{-$locale}/thank-you'
    | '/{-$locale}/unsubscribe'
    | '/{-$locale}/'
    | '/{-$locale}/catalogue/$slug'
    | '/{-$locale}/catalogue/success'
    | '/{-$locale}/destinations/norway'
    | '/{-$locale}/itineraries-shop/$slug'
    | '/{-$locale}/itineraries-shop/success'
    | '/{-$locale}/routes/$slug'
    | '/{-$locale}/trip/$token'
    | '/{-$locale}/catalogue/'
    | '/{-$locale}/itineraries-shop/'
    | '/{-$locale}/routes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/{-$locale}/about'
    | '/{-$locale}/admin'
    | '/{-$locale}/legal'
    | '/{-$locale}/login'
    | '/{-$locale}/plan-my-trip'
    | '/{-$locale}/privacy'
    | '/{-$locale}/reset-password'
    | '/{-$locale}/start-your-journey'
    | '/{-$locale}/terms'
    | '/{-$locale}/thank-you'
    | '/{-$locale}/unsubscribe'
    | '/{-$locale}'
    | '/{-$locale}/catalogue/$slug'
    | '/{-$locale}/catalogue/success'
    | '/{-$locale}/destinations/norway'
    | '/{-$locale}/itineraries-shop/$slug'
    | '/{-$locale}/itineraries-shop/success'
    | '/{-$locale}/routes/$slug'
    | '/{-$locale}/trip/$token'
    | '/{-$locale}/catalogue'
    | '/{-$locale}/itineraries-shop'
    | '/{-$locale}/routes'
  id:
    | '__root__'
    | '/{-$locale}'
    | '/{-$locale}/about'
    | '/{-$locale}/admin'
    | '/{-$locale}/legal'
    | '/{-$locale}/login'
    | '/{-$locale}/plan-my-trip'
    | '/{-$locale}/privacy'
    | '/{-$locale}/reset-password'
    | '/{-$locale}/start-your-journey'
    | '/{-$locale}/terms'
    | '/{-$locale}/thank-you'
    | '/{-$locale}/unsubscribe'
    | '/{-$locale}/'
    | '/{-$locale}/catalogue/$slug'
    | '/{-$locale}/catalogue/success'
    | '/{-$locale}/destinations/norway'
    | '/{-$locale}/itineraries-shop/$slug'
    | '/{-$locale}/itineraries-shop/success'
    | '/{-$locale}/routes/$slug'
    | '/{-$locale}/trip/$token'
    | '/{-$locale}/catalogue/'
    | '/{-$locale}/itineraries-shop/'
    | '/{-$locale}/routes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  Char123LocaleChar125Route: typeof Char123LocaleChar125RouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/{-$locale}': {
      id: '/{-$locale}'
      path: '/{-$locale}'
      fullPath: '/{-$locale}'
      preLoaderRoute: typeof Char123LocaleChar125RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/': {
      id: '/{-$locale}/'
      path: '/'
      fullPath: '/{-$locale}/'
      preLoaderRoute: typeof Char123LocaleChar125IndexRouteImport
      parentRoute: typeof Char123LocaleChar125Route
    }
    '/{-$locale}/about': {
      id: '/{-$locale}/about'
      path: '/about'
      fullPath: '/{-$locale}/about'
      preLoaderRoute: typeof Char123LocaleChar125AboutRouteImport
      parentRoute: typeof Char123LocaleChar125Route
    }
    '/{-$locale}/admin': {
      id: '/{-$locale}/admin'
      path: '/admin'
      fullPath: '/{-$locale}/admin'
      preLoaderRoute: typeof Char123LocaleChar125AdminRouteImport
      parentRoute: typeof Char123LocaleChar125Route
    }
    '/{-$locale}/legal': {
      id: '/{-$locale}/legal'
      path: '/legal'
      fullPath: '/{-$locale}/legal'
      preLoaderRoute: typeof Char123LocaleChar125LegalRouteImport
      parentRoute: typeof Char123LocaleChar125Route
    }
    '/{-$locale}/login': {
      id: '/{-$locale}/login'
      path: '/login'
      fullPath: '/{-$locale}/login'
      preLoaderRoute: typeof Char123LocaleChar125LoginRouteImport
      parentRoute: typeof Char123LocaleChar125Route
    }
    '/{-$locale}/plan-my-trip': {
      id: '/{-$locale}/plan-my-trip'
      path: '/plan-my-trip'
      fullPath: '/{-$locale}/plan-my-trip'
      preLoaderRoute: typeof Char123LocaleChar125PlanMyTripRouteImport
      parentRoute: typeof Char123LocaleChar125Route
    }
    '/{-$locale}/privacy': {
      id: '/{-$locale}/privacy'
      path: '/privacy'
      fullPath: '/{-$locale}/privacy'
      preLoaderRoute: typeof Char123LocaleChar125PrivacyRouteImport
      parentRoute: typeof Char123LocaleChar125Route
    }
    '/{-$locale}/reset-password': {
      id: '/{-$locale}/reset-password'
      path: '/reset-password'
      fullPath: '/{-$locale}/reset-password'
      preLoaderRoute: typeof Char123LocaleChar125ResetPasswordRouteImport
      parentRoute: typeof Char123LocaleChar125Route
    }
    '/{-$locale}/start-your-journey': {
      id: '/{-$locale}/start-your-journey'
      path: '/start-your-journey'
      fullPath: '/{-$locale}/start-your-journey'
      preLoaderRoute: typeof Char123LocaleChar125StartYourJourneyRouteImport
      parentRoute: typeof Char123LocaleChar125Route
    }
    '/{-$locale}/terms': {
      id: '/{-$locale}/terms'
      path: '/terms'
      fullPath: '/{-$locale}/terms'
      preLoaderRoute: typeof Char123LocaleChar125TermsRouteImport
      parentRoute: typeof Char123LocaleChar125Route
    }
    '/{-$locale}/thank-you': {
      id: '/{-$locale}/thank-you'
      path: '/thank-you'
      fullPath: '/{-$locale}/thank-you'
      preLoaderRoute: typeof Char123LocaleChar125ThankYouRouteImport
      parentRoute: typeof Char123LocaleChar125Route
    }
    '/{-$locale}/unsubscribe': {
      id: '/{-$locale}/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/{-$locale}/unsubscribe'
      preLoaderRoute: typeof Char123LocaleChar125UnsubscribeRouteImport
      parentRoute: typeof Char123LocaleChar125Route
    }
    '/{-$locale}/catalogue/': {
      id: '/{-$locale}/catalogue/'
      path: '/catalogue'
      fullPath: '/{-$locale}/catalogue/'
      preLoaderRoute: typeof Char123LocaleChar125CatalogueIndexRouteImport
      parentRoute: typeof Char123LocaleChar125Route
    }
    '/{-$locale}/catalogue/$slug': {
      id: '/{-$locale}/catalogue/$slug'
      path: '/catalogue/$slug'
      fullPath: '/{-$locale}/catalogue/$slug'
      preLoaderRoute: typeof Char123LocaleChar125CatalogueSlugRouteImport
      parentRoute: typeof Char123LocaleChar125Route
    }
    '/{-$locale}/catalogue/success': {
      id: '/{-$locale}/catalogue/success'
      path: '/catalogue/success'
      fullPath: '/{-$locale}/catalogue/success'
      preLoaderRoute: typeof Char123LocaleChar125CatalogueSuccessRouteImport
      parentRoute: typeof Char123LocaleChar125Route
    }
    '/{-$locale}/destinations/norway': {
      id: '/{-$locale}/destinations/norway'
      path: '/destinations/norway'
      fullPath: '/{-$locale}/destinations/norway'
      preLoaderRoute: typeof Char123LocaleChar125DestinationsNorwayRouteImport
      parentRoute: typeof Char123LocaleChar125Route
    }
    '/{-$locale}/itineraries-shop/': {
      id: '/{-$locale}/itineraries-shop/'
      path: '/itineraries-shop'
      fullPath: '/{-$locale}/itineraries-shop/'
      preLoaderRoute: typeof Char123LocaleChar125ItinerariesShopIndexRouteImport
      parentRoute: typeof Char123LocaleChar125Route
    }
    '/{-$locale}/itineraries-shop/$slug': {
      id: '/{-$locale}/itineraries-shop/$slug'
      path: '/itineraries-shop/$slug'
      fullPath: '/{-$locale}/itineraries-shop/$slug'
      preLoaderRoute: typeof Char123LocaleChar125ItinerariesShopSlugRouteImport
      parentRoute: typeof Char123LocaleChar125Route
    }
    '/{-$locale}/itineraries-shop/success': {
      id: '/{-$locale}/itineraries-shop/success'
      path: '/itineraries-shop/success'
      fullPath: '/{-$locale}/itineraries-shop/success'
      preLoaderRoute: typeof Char123LocaleChar125ItinerariesShopSuccessRouteImport
      parentRoute: typeof Char123LocaleChar125Route
    }
    '/{-$locale}/routes/': {
      id: '/{-$locale}/routes/'
      path: '/routes'
      fullPath: '/{-$locale}/routes/'
      preLoaderRoute: typeof Char123LocaleChar125RoutesIndexRouteImport
      parentRoute: typeof Char123LocaleChar125Route
    }
    '/{-$locale}/routes/$slug': {
      id: '/{-$locale}/routes/$slug'
      path: '/routes/$slug'
      fullPath: '/{-$locale}/routes/$slug'
      preLoaderRoute: typeof Char123LocaleChar125RoutesSlugRouteImport
      parentRoute: typeof Char123LocaleChar125Route
    }
    '/{-$locale}/trip/$token': {
      id: '/{-$locale}/trip/$token'
      path: '/trip/$token'
      fullPath: '/{-$locale}/trip/$token'
      preLoaderRoute: typeof Char123LocaleChar125TripTokenRouteImport
      parentRoute: typeof Char123LocaleChar125Route
    }
  }
}

interface Char123LocaleChar125RouteChildren {
  Char123LocaleChar125AboutRoute: typeof Char123LocaleChar125AboutRoute
  Char123LocaleChar125AdminRoute: typeof Char123LocaleChar125AdminRoute
  Char123LocaleChar125LegalRoute: typeof Char123LocaleChar125LegalRoute
  Char123LocaleChar125LoginRoute: typeof Char123LocaleChar125LoginRoute
  Char123LocaleChar125PlanMyTripRoute: typeof Char123LocaleChar125PlanMyTripRoute
  Char123LocaleChar125PrivacyRoute: typeof Char123LocaleChar125PrivacyRoute
  Char123LocaleChar125ResetPasswordRoute: typeof Char123LocaleChar125ResetPasswordRoute
  Char123LocaleChar125StartYourJourneyRoute: typeof Char123LocaleChar125StartYourJourneyRoute
  Char123LocaleChar125TermsRoute: typeof Char123LocaleChar125TermsRoute
  Char123LocaleChar125ThankYouRoute: typeof Char123LocaleChar125ThankYouRoute
  Char123LocaleChar125UnsubscribeRoute: typeof Char123LocaleChar125UnsubscribeRoute
  Char123LocaleChar125IndexRoute: typeof Char123LocaleChar125IndexRoute
  Char123LocaleChar125CatalogueSlugRoute: typeof Char123LocaleChar125CatalogueSlugRoute
  Char123LocaleChar125CatalogueSuccessRoute: typeof Char123LocaleChar125CatalogueSuccessRoute
  Char123LocaleChar125DestinationsNorwayRoute: typeof Char123LocaleChar125DestinationsNorwayRoute
  Char123LocaleChar125ItinerariesShopSlugRoute: typeof Char123LocaleChar125ItinerariesShopSlugRoute
  Char123LocaleChar125ItinerariesShopSuccessRoute: typeof Char123LocaleChar125ItinerariesShopSuccessRoute
  Char123LocaleChar125RoutesSlugRoute: typeof Char123LocaleChar125RoutesSlugRoute
  Char123LocaleChar125TripTokenRoute: typeof Char123LocaleChar125TripTokenRoute
  Char123LocaleChar125CatalogueIndexRoute: typeof Char123LocaleChar125CatalogueIndexRoute
  Char123LocaleChar125ItinerariesShopIndexRoute: typeof Char123LocaleChar125ItinerariesShopIndexRoute
  Char123LocaleChar125RoutesIndexRoute: typeof Char123LocaleChar125RoutesIndexRoute
}

const Char123LocaleChar125RouteChildren: Char123LocaleChar125RouteChildren = {
  Char123LocaleChar125AboutRoute: Char123LocaleChar125AboutRoute,
  Char123LocaleChar125AdminRoute: Char123LocaleChar125AdminRoute,
  Char123LocaleChar125LegalRoute: Char123LocaleChar125LegalRoute,
  Char123LocaleChar125LoginRoute: Char123LocaleChar125LoginRoute,
  Char123LocaleChar125PlanMyTripRoute: Char123LocaleChar125PlanMyTripRoute,
  Char123LocaleChar125PrivacyRoute: Char123LocaleChar125PrivacyRoute,
  Char123LocaleChar125ResetPasswordRoute:
    Char123LocaleChar125ResetPasswordRoute,
  Char123LocaleChar125StartYourJourneyRoute:
    Char123LocaleChar125StartYourJourneyRoute,
  Char123LocaleChar125TermsRoute: Char123LocaleChar125TermsRoute,
  Char123LocaleChar125ThankYouRoute: Char123LocaleChar125ThankYouRoute,
  Char123LocaleChar125UnsubscribeRoute: Char123LocaleChar125UnsubscribeRoute,
  Char123LocaleChar125IndexRoute: Char123LocaleChar125IndexRoute,
  Char123LocaleChar125CatalogueSlugRoute:
    Char123LocaleChar125CatalogueSlugRoute,
  Char123LocaleChar125CatalogueSuccessRoute:
    Char123LocaleChar125CatalogueSuccessRoute,
  Char123LocaleChar125DestinationsNorwayRoute:
    Char123LocaleChar125DestinationsNorwayRoute,
  Char123LocaleChar125ItinerariesShopSlugRoute:
    Char123LocaleChar125ItinerariesShopSlugRoute,
  Char123LocaleChar125ItinerariesShopSuccessRoute:
    Char123LocaleChar125ItinerariesShopSuccessRoute,
  Char123LocaleChar125RoutesSlugRoute: Char123LocaleChar125RoutesSlugRoute,
  Char123LocaleChar125TripTokenRoute: Char123LocaleChar125TripTokenRoute,
  Char123LocaleChar125CatalogueIndexRoute:
    Char123LocaleChar125CatalogueIndexRoute,
  Char123LocaleChar125ItinerariesShopIndexRoute:
    Char123LocaleChar125ItinerariesShopIndexRoute,
  Char123LocaleChar125RoutesIndexRoute: Char123LocaleChar125RoutesIndexRoute,
}

const Char123LocaleChar125RouteWithChildren =
  Char123LocaleChar125Route._addFileChildren(Char123LocaleChar125RouteChildren)

const rootRouteChildren: RootRouteChildren = {
  Char123LocaleChar125Route: Char123LocaleChar125RouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
